language: rust

rust: stable

env:
  global:
    - RUST_LOG=info

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      name: run rustfmt
      script:
        - make install-rustfmt
        - make ci-lint

    - stage: test
      name: run test
      rust: nightly
      script:
        - make ci-test

    - stage: test
      name: run coverage
      script:
        - make install-tarpaulin
        - make ci-coverage
